//! 两种指定配卡的纯手写真实属性边际矩阵；不改变恢复、外出、吃面等结构。
use std::{env,path::Path};
use anyhow::{Context,Result};use serde::Serialize;
use umasim::{bench::{self,CardPickOpts,DeckComposition},game::{Game,InheritInfo,ramen::RamenGame},gamedata::init_global_with_config,trainer::RecommendedRamenTrainer,utils::{get_workspace_root,load_game_config}};
const UMA:u32=102601;const FRIEND:u32=303054;const INHERIT:InheritInfo=InheritInfo{blue_count:[15,0,0,0,3],extra_count:[10,10,20,20,20,40]};
const LEVELS:[u32;5]=[0,25,50,75,100];
#[derive(Serialize)]struct Row{build:String,variant:String,gap:u32,overflow:u32,run:u64,score:i32,skill_pt:i32,scenario_pt:i32,five_sum:i32,speed:i32,stamina:i32,power:i32,guts:i32,wisdom:i32}
fn deck(name:&str)->Result<[u32;6]>{let counts=match name{"3速1耐1智"=>[3,1,0,0,1],"2速2耐1智"=>[2,2,0,0,1],_=>anyhow::bail!("未知配卡 {name}")};DeckComposition{counts,name:name.into()}.build_deck(&bench::select_representatives(&CardPickOpts::default())?.picked,FRIEND)}
fn candidate(gap:u32,over:u32)->RecommendedRamenTrainer{RecommendedRamenTrainer::with_experiment_overrides([16.0,64.0,64.0],gap as f32/100.0,over as f32/100.0,140.0,0.10,40.0,8.0,6.0)}
fn push(rows:&mut Vec<Row>,build:&str,variant:&str,gap:u32,overflow:u32,run:u64,g:&RamenGame){let s=g.uma.five_status;rows.push(Row{build:build.into(),variant:variant.into(),gap,overflow,run,score:g.uma.calc_score(),skill_pt:g.uma.skill_pt,scenario_pt:g.ramen.scenario_pt,five_sum:s.iter().sum(),speed:s[0],stamina:s[1],power:s[2],guts:s[3],wisdom:s[4]})}
fn main()->Result<()>{env::set_current_dir(get_workspace_root()?)?;init_global_with_config(&load_game_config()?)?;let build=env::var("BUILD").context("缺少 BUILD")?;let shard:u64=env::var("SHARD").unwrap_or_else(|_|"0".into()).parse()?;let runs:u64=env::var("RUNS").unwrap_or_else(|_|"20".into()).parse()?;let seed:u64=env::var("BASE_SEED").unwrap_or_else(|_|"939393".into()).parse()?;let deck=deck(&build)?;let mut rows=Vec::new();for off in 0..runs{let run=shard*runs+off;let(mut rng,master)=bench::seeded_rngs(seed,run);let mut g=RamenGame::newgame(UMA,&deck,INHERIT)?;g.set_rule_master(master);g.run_full_game(&RecommendedRamenTrainer::new(),&mut rng)?;push(&mut rows,&build,"baseline",0,0,run,&g);for gap in LEVELS{for over in LEVELS{if gap==0&&over==0{continue}let(mut rng,master)=bench::seeded_rngs(seed,run);let mut g=RamenGame::newgame(UMA,&deck,INHERIT)?;g.set_rule_master(master);g.run_full_game(&candidate(gap,over),&mut rng)?;push(&mut rows,&build,"margin",gap,over,run,&g);}}}let mut w=csv::Writer::from_path(Path::new("focused-status-margin.csv"))?;for r in rows{w.serialize(r)?}w.flush()?;Ok(())}
