//! 当前正式手写策略 vs 扁平蒙特卡洛：Train 阶段非侵入式 regret / 体力审计。
use std::{env,path::Path,sync::Mutex};
use anyhow::{Context,Result}; use rand::prelude::StdRng; use serde::Serialize;
use umasim::{bench::{self,CardPickOpts,DeckComposition},game::{Game,InheritInfo,Trainer,ramen::{Operation,RamenAction,RamenGame,RamenStage}},gamedata::{EventChoice,EventData,init_global_with_config},search::{FlatSearch,SearchConfig},trainer::RecommendedRamenTrainer,utils::{get_workspace_root,load_game_config}};
const UMA:u32=102601;const FRIEND:u32=303054;const INHERIT:InheritInfo=InheritInfo{blue_count:[15,0,0,0,3],extra_count:[10,10,20,20,20,40]};
#[derive(Serialize,Clone)]struct DecisionRow{build:String,run:u64,turn:i32,year:i32,vital:i32,max_vital:i32,hand_action:String,teacher_action:String,agree:bool,radical_factor:f64,hand_mean:f64,teacher_mean:f64,hand_weighted:f64,teacher_weighted:f64,regret:f64,hand_post_vital:String,teacher_post_vital:String,hand_recovery:bool,teacher_recovery:bool,transition:String}
#[derive(Serialize)]struct GameRow{build:String,run:u64,score:i32,skill_pt:i32,speed:i32,stamina:i32,power:i32,guts:i32,wisdom:i32,searched:usize,disagree:usize,total_regret:f64,recovery_disagree:usize}
struct AuditTrainer{inner:RecommendedRamenTrainer,search:FlatSearch<RamenGame>,build:String,run:u64,rows:Mutex<Vec<DecisionRow>>}
impl AuditTrainer{
 fn post(g:&RamenGame,a:&RamenAction)->Result<Option<i32>>{Ok(match a.operation{Operation::Train(tt)=>{let t=tt as usize;let b=g.calc_training_buff(t)?;Some(g.uma.vital+g.calc_training_value(&b,t)?.vital)},Operation::Rest=>Some(g.uma.max_vital.min(g.uma.vital+50)),_=>None})}
 fn recovery(a:&RamenAction)->bool{matches!(a.operation,Operation::Rest|Operation::FriendOuting|Operation::NormalOuting)}
 fn kind(a:&RamenAction)->&'static str{match a.operation{Operation::Train(_)=>"训练",Operation::Rest=>"休息",Operation::FriendOuting=>"友人外出",Operation::NormalOuting=>"普通外出",Operation::Clinic=>"诊所",Operation::Race=>"比赛",_=>"其他"}}
}
impl Trainer<RamenGame> for AuditTrainer{
 fn select_action(&self,g:&RamenGame,a:&[RamenAction],rng:&mut StdRng)->Result<usize>{let hand=self.inner.select_action(g,a,rng)?;if g.stage==RamenStage::Train&&a.len()>1{let mut shadow=rng.clone();let out=self.search.search(g,a,&mut shadow)?;let teacher=out.best_action_idx;let rf=out.radical_factor;let hm=out.action_results[hand].0.mean();let tm=out.action_results[teacher].0.mean();let hw=out.action_results[hand].0.weighted_mean(rf);let tw=out.action_results[teacher].0.weighted_mean(rf);let hr=Self::recovery(&a[hand]);let tr=Self::recovery(&a[teacher]);let row=DecisionRow{build:self.build.clone(),run:self.run,turn:g.turn(),year:g.current_year(),vital:g.uma.vital,max_vital:g.uma.max_vital,hand_action:format!("{:?}",a[hand].operation),teacher_action:format!("{:?}",a[teacher].operation),agree:hand==teacher,radical_factor:rf,hand_mean:hm,teacher_mean:tm,hand_weighted:hw,teacher_weighted:tw,regret:(tw-hw).max(0.0),hand_post_vital:Self::post(g,&a[hand])?.map_or_else(||"未知".into(),|x|x.to_string()),teacher_post_vital:Self::post(g,&a[teacher])?.map_or_else(||"未知".into(),|x|x.to_string()),hand_recovery:hr,teacher_recovery:tr,transition:format!("{}→{}",Self::kind(&a[hand]),Self::kind(&a[teacher]))};self.rows.lock().map_err(|_|anyhow::anyhow!("审计锁损坏"))?.push(row);}Ok(hand)}
 fn select_choice(&self,g:&RamenGame,c:&[Vec<EventChoice>],r:&mut StdRng)->Result<usize>{self.inner.select_choice(g,c,r)}fn select_event_choice(&self,g:&RamenGame,e:&EventData,c:&[Vec<EventChoice>],r:&mut StdRng)->Result<usize>{self.inner.select_event_choice(g,e,c,r)}
}
fn deck(name:&str)->Result<[u32;6]>{let counts=match name{"3速1耐1智"=>[3,1,0,0,1],"2速2耐1智"=>[2,2,0,0,1],_=>anyhow::bail!("未知配卡 {name}")};DeckComposition{counts,name:name.into()}.build_deck(&bench::select_representatives(&CardPickOpts::default())?.picked,FRIEND)}
fn main()->Result<()>{env::set_current_dir(get_workspace_root()?)?;init_global_with_config(&load_game_config()?)?;let build=env::var("BUILD").context("缺少 BUILD")?;let shard:u64=env::var("SHARD").unwrap_or_else(|_|"0".into()).parse()?;let runs:u64=env::var("RUNS").unwrap_or_else(|_|"2".into()).parse()?;let n:usize=env::var("SEARCH_N").unwrap_or_else(|_|"128".into()).parse()?;let base:u64=env::var("BASE_SEED").unwrap_or_else(|_|"717171".into()).parse()?;let deck=deck(&build)?;let(mut decisions,mut games)=(Vec::new(),Vec::new());for off in 0..runs{let run=shard*runs+off;let(mut rng,master)=bench::seeded_rngs(base,run);let mut g=RamenGame::newgame(UMA,&deck,INHERIT)?;g.set_rule_master(master);let t=AuditTrainer{inner:RecommendedRamenTrainer::new(),search:FlatSearch::new(SearchConfig::default().with_search_n(n).with_ucb(false)),build:build.clone(),run,rows:Mutex::new(Vec::new())};g.run_full_game(&t,&mut rng)?;let rows=t.rows.into_inner().map_err(|_|anyhow::anyhow!("审计锁损坏"))?;let s=g.uma.five_status;games.push(GameRow{build:build.clone(),run,score:g.uma.calc_score(),skill_pt:g.uma.skill_pt,speed:s[0],stamina:s[1],power:s[2],guts:s[3],wisdom:s[4],searched:rows.len(),disagree:rows.iter().filter(|x|!x.agree).count(),total_regret:rows.iter().map(|x|x.regret).sum(),recovery_disagree:rows.iter().filter(|x|x.hand_recovery!=x.teacher_recovery).count()});decisions.extend(rows)}let mut w=csv::Writer::from_path(Path::new("train-regret-decisions.csv"))?;for r in decisions{w.serialize(r)?}w.flush()?;let mut w=csv::Writer::from_path(Path::new("train-regret-games.csv"))?;for r in games{w.serialize(r)?}w.flush()?;Ok(())}
