//! 当前正式策略 vs Train 阶段统一终局搜索 AB。
use std::{env,path::Path,sync::atomic::{AtomicUsize,Ordering}};
use anyhow::{Context,Result};use rand::prelude::StdRng;use serde::Serialize;
use umasim::{bench::{self,CardPickOpts,DeckComposition},game::{Game,InheritInfo,Trainer,ramen::{Operation,RamenAction,RamenGame,RamenStage}},gamedata::{EventChoice,EventData,init_global_with_config},search::{FlatSearch,SearchConfig},trainer::RecommendedRamenTrainer,utils::{get_workspace_root,load_game_config}};
const UMA:u32=102601;const FRIEND:u32=303054;const INHERIT:InheritInfo=InheritInfo{blue_count:[15,0,0,0,3],extra_count:[10,10,20,20,20,40]};
struct Unified{base:RecommendedRamenTrainer,search:FlatSearch<RamenGame>,searched:AtomicUsize,rest:AtomicUsize,friend:AtomicUsize,outing:AtomicUsize,train:AtomicUsize}
impl Unified{fn new(n:usize)->Self{Self{base:RecommendedRamenTrainer::new(),search:FlatSearch::new(SearchConfig::default().with_search_n(n).with_ucb(false)),searched:AtomicUsize::new(0),rest:AtomicUsize::new(0),friend:AtomicUsize::new(0),outing:AtomicUsize::new(0),train:AtomicUsize::new(0)}}fn count(&self,a:&RamenAction){match a.operation{Operation::Rest=>{self.rest.fetch_add(1,Ordering::Relaxed);},Operation::FriendOuting=>{self.friend.fetch_add(1,Ordering::Relaxed);},Operation::NormalOuting=>{self.outing.fetch_add(1,Ordering::Relaxed);},Operation::Train(_)=>{self.train.fetch_add(1,Ordering::Relaxed);},_=>{}}}}
impl Trainer<RamenGame> for Unified{
 fn select_action(&self,g:&RamenGame,a:&[RamenAction],rng:&mut StdRng)->Result<usize>{let idx=if g.stage==RamenStage::Train&&a.len()>1{let mut shadow=rng.clone();self.searched.fetch_add(1,Ordering::Relaxed);self.search.search(g,a,&mut shadow)?.best_action_idx}else{self.base.select_action(g,a,rng)?};if g.stage==RamenStage::Train{self.count(&a[idx]);}Ok(idx)}
 fn select_choice(&self,g:&RamenGame,c:&[Vec<EventChoice>],r:&mut StdRng)->Result<usize>{self.base.select_choice(g,c,r)}
 fn select_event_choice(&self,g:&RamenGame,e:&EventData,c:&[Vec<EventChoice>],r:&mut StdRng)->Result<usize>{self.base.select_event_choice(g,e,c,r)}
}
#[derive(Serialize)]struct Row{build:String,variant:String,run:u64,score:i32,skill_pt:i32,speed:i32,stamina:i32,power:i32,guts:i32,wisdom:i32,five_sum:i32,searched:usize,train:usize,rest:usize,friend_outing:usize,normal_outing:usize}
fn deck(name:&str)->Result<[u32;6]>{let counts=match name{"3速1耐1智"=>[3,1,0,0,1],"2速2耐1智"=>[2,2,0,0,1],_=>anyhow::bail!("未知配卡 {name}")};DeckComposition{counts,name:name.into()}.build_deck(&bench::select_representatives(&CardPickOpts::default())?.picked,FRIEND)}
fn main()->Result<()>{env::set_current_dir(get_workspace_root()?)?;init_global_with_config(&load_game_config()?)?;let build=env::var("BUILD").context("缺少 BUILD")?;let variant=env::var("VARIANT").context("缺少 VARIANT")?;let shard:u64=env::var("SHARD").unwrap_or_else(|_|"0".into()).parse()?;let runs:u64=env::var("RUNS").unwrap_or_else(|_|"5".into()).parse()?;let n:usize=env::var("SEARCH_N").unwrap_or_else(|_|"128".into()).parse()?;let base_seed:u64=env::var("BASE_SEED").unwrap_or_else(|_|"828282".into()).parse()?;let deck=deck(&build)?;let mut rows=Vec::new();for off in 0..runs{let run=shard*runs+off;let(mut rng,master)=bench::seeded_rngs(base_seed,run);let mut g=RamenGame::newgame(UMA,&deck,INHERIT)?;g.set_rule_master(master);let(searched,train,rest,friend,outing)=if variant=="baseline"{let t=RecommendedRamenTrainer::new();g.run_full_game(&t,&mut rng)?;(0,0,0,0,0)}else if variant=="unified-search"{let t=Unified::new(n);g.run_full_game(&t,&mut rng)?;(t.searched.load(Ordering::Relaxed),t.train.load(Ordering::Relaxed),t.rest.load(Ordering::Relaxed),t.friend.load(Ordering::Relaxed),t.outing.load(Ordering::Relaxed))}else{anyhow::bail!("未知方案 {variant}")};let s=g.uma.five_status;rows.push(Row{build:build.clone(),variant:variant.clone(),run,score:g.uma.calc_score(),skill_pt:g.uma.skill_pt,speed:s[0],stamina:s[1],power:s[2],guts:s[3],wisdom:s[4],five_sum:s.iter().sum(),searched,train,rest,friend_outing:friend,normal_outing:outing});}let mut w=csv::Writer::from_path(Path::new("unified-train-search-ab.csv"))?;for r in rows{w.serialize(r)?}w.flush()?;Ok(())}
